{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-app.fullname" . }}-postgres-secret
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: postgres
type: Opaque
data:
  postgres-user: {{ .Values.postgres.username | b64enc }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
{{- end }}
